### ISSUE TITLE
Question: How to I port tags from Allusion over to OneFolder?

### ISSUE THREAD

**Issue by ghostsquad** [OneFolderApp/OneFolder#7]
My question is, how would I port tags from Allusion over to this app, if I intend on adopting this due to active development?

**Comment by Antoine-lb** [comment]
Hello, sorry for the late response. You only need to export tags in the settings of Allusion, then import them back in OneFolder

**Comment by ghostsquad** [comment]
Thanks! I didn't realize export was part of settings.
