### ISSUE TITLE
Virus detected on VirusTotal.

### ISSUE THREAD

**Issue by Gord067** [OneFolderApp/OneFolder#82]
I downloaded the new version and submitted it to VirusTotal.  VirusTotal detected W32.AIDetectMalware in the file. It was identified by Bkav Pro.  It may be a false positive, can you look into this and verify it for us.

Thanks,
Gord

![Screenshot 2024-06-30 at 18-09-54 VirusTotal - File - d6cae3ab0c32e9a19406eeb4fa1d94a689e747e1aa0cece8c63439ab40458f62](https://github.com/OneFolderApp/OneFolder/assets/170283229/7b185d71-e26d-4a2e-9cf9-6f7c0b91231c)

**Comment by Antoine-lb** [comment]
Hello, thanks for pointing this out, I will look into this. Do you have a security background?

**Comment by Gord067** [comment]
I ran the latest OneFolder release, the Linux 1.0.11 appimage though VirusTotal and no viruses were detected.  I think that the earlier malicious flagging was probably false.

**Comment by Antoine-lb** [comment]
Or maybe a dependency got updated. This type of software can have a staggering amount of dependencies (1000s), bc dependecies have their own dependecies and so on. Sometime just updating a package fixes the issue.

But thanks for pointing it out 🙏
