### ISSUE TITLE
Auto-update error on Linux

### ISSUE THREAD

**Issue by Gord067** [OneFolderApp/OneFolder#83]
When I use the "check for updates" function I get an error

**To Reproduce**

1. Launch OneFolder
2. Click on the 3 dots menu, upper left corner, then click the "check for updates" function.
3. See error

**Expected behavior**
A update check would occur and the results displayed.

**Screenshots**
![20240701 screenshot OneFolder auto-update error](https://github.com/OneFolderApp/OneFolder/assets/170283229/cd806f93-3c06-480a-9955-f305a290d030)

**OneFolder version**

- I beileve it is v1.0.0 (the about menu is not available in my install)

**Desktop OS**

MX Linux 23.3 KDE 64bit

**Additional context**

**Comment by Antoine-lb** [comment]
We are missing the `latest-linux.yml`, I don't really know why. I will check this

**Comment by Gord067** [comment]
Thanks.  As I am moving to Linux full time I will notify you of any further
problems.

Gord

**Comment by Antoine-lb** [comment]
Yes thank you, bc we don't have a linux computer. But we have a old iMac laying around, we are probably going to format it so we can test ourselvs

**Comment by senntore** [comment]
I can't find linux version in the latest releases. Is this issue related to that?

**Comment by Antoine-lb** [comment]
Most likely yes, I will get to this next week

**Comment by Gord067** [comment]
I have downloaded and installed the latest release, 1.0.11 linux appimage.  I tried the update feature to see what would happen and it seems to be working. A dialog box opened informing me that there are no updates available and that I have the current version, which is what I expected.  There were no error messages.  Hopefully the problem is resolved.

**Comment by Antoine-lb** [comment]
This should be fixed. I have yet to update the website to the latest version.

I will close this for now, if there are new issues don't hesitate to create an issue
