### ISSUE TITLE
Two issues (loading thumbnails and importing folders)

### ISSUE THREAD

**Issue by Rsfinder** [OneFolderApp/OneFolder#84]
I have recently learned about OneFolder.
I already knew about Allusion, so I am glad to see that such software is still around!

After using OneFolder for a few days, I felt that the following issues should be prioritized for resolution
・Every time I scroll or select another folder, the thumbnails load.
・When I try to import many folders (+ subfolders), it sometimes does not do them.

This could be solved with a better index and database, as answered in past questions.

I think a better method....would be to create an index of folder paths + file names in one step first, like [Everything](https://www.voidtools.com/) , and then create thumbnails in order.
(But this is a layman's idea; Everything is not open source, and it would not be easy to index a large number of files in a fast way.

Combine a UI-UX like Eagle, indexing and search power like Everything, and manageability like Picasa, and you have a great tool.

I can only support this with feature ideas and feedback from other tools,
but I hope OneFolder will be a great management software more than anything else🙏

**Comment by Antoine-lb** [comment]
Hello 👋

> - Every time I scroll or select another folder, the thumbnails load

You mean that it loads even if it has already loaded before?

> - When I try to import many folders (+ subfolders), it sometimes does not do them.

How many are we talking about?

"Everything" looks like a fantastic tool, I will play with it to see it in action.

> but I hope OneFolder will be a great management software more than anything else🙏

Thanks! this types of media rich applications are a lot of work. Seeing people use it is a real pleasure.

**Comment by Rsfinder** [comment]
Thanks for the answer!
I was a little short on my explanation.

Thumbnail loading <this refers to the thumbnail loading that occurs when scrolling fast or switching folders.
It can be a little stressful to have loading occur over and over again.

I think it would be nice to have as little loading as possible when switching and scrolling like this.
https://github.com/user-attachments/assets/89062f08-3dbf-4bd1-adbf-2cfbec66bb75

Loading multiple folders <This is not an error, 
but rather an event that can take a considerable amount of time if the number of folders-subfolders-files is large.

ex, 
１ category folder ② person's name folder (100) ③ files (50~1000),
There is no problem to import ② as it is.
but, there was no sign of importing when I tried to put them together from (1).


As expected, importing ② one by one is very costly, and there are many more files than in the example. So I thought it would be smoother if an index like Everything could be created.

In addition to Everything, I would like to list some other software that would be helpful.

[Everything](https://www.voidtools.com/) - indexing, fast search
[Eagle](https://eagle.cool/) - support for many extensions, Superior UI-UX, sortability
[Picasa](https://picasa.softonic.com/) - editing capabilities, excellent manageability
[Tonfotos](https://tonfotos.com/) - simple and low memory consumption (good database?)

I feel that if it could be indexed at high speed and integrated into a database, it would greatly increase the amount of imports and search power, and allow for smooth file checking (Not an easy task...🙄

**Comment by Antoine-lb** [comment]
Hello, thanks for all the details!

Regarding the loading, it will be a tough problem to solve. Thumbnails are generated when you import and not on the fly to make them faster. So I don't have many ideas on how to make it faster, but I'm open to ideas.

Regarding the second problem I would like to dig a little to see what is going on.

- How many files are we talking in total? with all the sub-folders.
- What are your computer's specs, how much RAM do you have?
- Have you tried waiting for a bit longer after everything loads. Even if the app says it's done, there are still things going on in the background (like the thumbnails). Maybe adding everything and waiting a bit longer can aliviate the problem

> I feel that if it could be indexed at high speed and integrated into a database, it would greatly increase the amount of imports and search power, and allow for smooth file checking (Not an easy task...🙄

Is not exactly one feature that will make things faster like a specific database. Is more like a bunch of little improuvments. It is indeed not an easy task, but we are motivated!

**Comment by Rsfinder** [comment]
Sorry for the late reply, I'll try to come up with some ideas for speeding up the process.

The import test I did was 100 folders about 20,000 files.
Specs are i5-11400F / RAM 32GB.

At the time of that test, I had to terminate it because I was not sure if the import was progressing properly after waiting 20~30 minutes, 
so I just did a new re-test. I waited for more than 30 minutes, but this time I got an error that disconnected in the middle of the process. It might be incompatibility with the NAS.
The cause of this is still unknown. It may happen only in my environment.

As a suggestion, it would be nice to have a gauge that shows the progress of the import.
The software I mentioned has such a function, so please consider it if you like.

I will report any other improvements or problems😌
