### ISSUE TITLE
Feature: random sorting like in Allusion

### ISSUE THREAD

**Issue by Aosneg** [OneFolderApp/OneFolder#88]
It would be nice to have a random sorting option like in Allusion
![image](https://github.com/user-attachments/assets/9f216ac8-7ff7-4644-8829-caf67e37feef)

**Comment by Antoine-lb** [comment]
I added it back, should be released soon.

**Comment by Aosneg** [comment]
Don't want to be annoying, but it seems you didn't add this feature with the last update. I also noticed that there was a similar feature request on your website dated March 22nd. So, it seemed to me that you might have just forgotten to include this feature in the release version, but it's already exist somewhere on your computer.

**Comment by Antoine-lb** [comment]
haha you are right, I forgot about it.

Here is v1.0.12 just for you

https://github.com/OneFolderApp/OneFolder/releases/tag/v1.0.12

Tell me if it works as intended

**Comment by Aosneg** [comment]
Just installed and it works as intended! Thanks for your work!
